### ISSUE TITLE
Accounts Maillist Fix

### ISSUE THREAD

**Issue by dat-adi** [Open-Source-Community-VIT-AP/oschub#50] opened 2021-04-16 17:25 UTC
**Describe the bug**
We receive an error `django.db.utils.OperationalError: no such table: accounts_maillist` due to maillist trying to access a table that doesn't yet exist upon first build.
A fix to this issue may be attempted by utilizing the try-except clauses.

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone the Django Project.
2. `python manage.py makemigrations`.
3. See error

**Expected behavior**
The Django Table for maillist should be created without any error popping up.

**Additional context**
The current workaround to this error is to,
1. Comment out the files SheetMe.py and `accounts/admin.py`.
2. `python manage.py makemigrations`
3. Uncomment and proceed on with life.

**Comment by kode-logger** [comment] 2021-04-16 17:56
## While making a new database, OperationalError: No Such Table … 

This error occurs when the table is not available in your database and some program scripts wants to access the table in the database to proceed further. 

Fix:

- Comment out all the scripts that use this specific table. (Eg: Commenting out SheetMe.py, admin.py [from all the django applications])
- Delete the database file (would recommend to do so as this error only occurs when you create a new database)
- Run `python manage.py migrate` : this will create the database and converts the changes to sqlite commands.
- Run `python manage.py makemigrations`: this will update any latest changes and updates the database with the sqlite commands.
- Uncomment all the scripts which you had previously commented out.

There is no permanent fix for this as this is only required at developing stage of the project. This error won't come up again unless we tamper with the Database manually by entering the Django commands to the console.

**Comment by SVijayB** [comment] 2021-04-16 18:50
> There is no permanent fix for this as this is only required at developing stage of the project. This error won't come up again unless we tamper with the Database manually by entering the Django commands to the console.

The problem is while deploying it on the server. Cannot push and migrate changes for each deployment.

**Comment by SVijayB** [comment] 2021-04-17 10:02
Since we've converted to PostgreSQL, we can close this issue as there won't be problems with migration anymore.

For future references:
If you plan to refresh the database follow steps below:
- Install heroku CLI.
- heroku run python manage.py migrate
- python manage.py migrate

As an alternative, you can also login to heroku and use their console and enter `python manage.py migrate`.

Once done, you are good to go.

**Closed** 2021-04-18 06:00 UTC
Labels: bug
