### ISSUE TITLE
SMTP Authentication Fails during Feedback POST.

### ISSUE THREAD

**Issue by dat-adi** [Open-Source-Community-VIT-AP/oschub#61] opened 2021-07-20 17:43 UTC
![image](https://user-images.githubusercontent.com/31721284/126370215-c4a7d475-06a0-4a16-ab94-821a3e6e3fe9.png)

SMTP Authentication seems to be unresolved as the users are unable to send a mail to the OSC's ID.
I suspect that the issue lies with the Google API not providing permission to send mails from the user's account.

However, this needs to be checked on, in the Django backend as well, in case it's an issue on both sides.

_Originally posted by @dat-adi in https://github.com/Open-Source-Community-VIT-AP/oschub/issues/60#issuecomment-883574587_

**Comment by kode-logger** [comment] 2021-07-20 17:48
Most probably the Google account that relays the mail to osc mail id has it's allow less secure apps option turned off. This might be the cause for the issue, I will look into it soon.

**Comment by kode-logger** [comment] 2021-07-23 09:02
I tried the feedback form after turning on the **Allow less secure apps** but still I was getting the same error.
Finally this might fix this issue: https://stackoverflow.com/a/56762489/14605652
I will fix this in a day or so.

**Comment by kode-logger** [comment] 2021-07-28 08:06
Commit 77850adb54d2b2f2319b359e4c5fb984f66e5776 Fixed the error. 
More on how to solve the error is given [here](https://github.com/Open-Source-Community-VIT-AP/oschub/wiki/ErrorGuide#feedback-form-smtp-authentication-error)
Hence closing this Issue.

**Closed by kode-logger** 2021-07-28 08:06 UTC
Labels: bug
